const queryKeys = {
  GET_MEMBERS: 'GET_MEMBERS',
  GET_INVITATIONS: 'GET_INVITATIONS',
  GET_DASHBOARD_SUMMARY: 'GET_DASHBOARD_SUMMARY',
  GET_DASHBOARD_ANALYTICS: 'GET_DASHBOARD_ANALYTICS',
  GET_PROJECTS: 'GET_PROJECTS',
  GET_TASKS: 'GET_TASKS',
} as const;

export default queryKeys;
